# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
ន
កំណែ៖"https://github.com/phonRathana/GitHubrathana/blob/2db01df8ac440e000aca53cf3ed623e47aabd791/.github/HTML.%20(<head><head>).SDK.come.android.application'
លេខ៖3
  - package-ecosystem: "4" 
"fingerprint":"Mw$0
    directory: "/" # map (11.5223822, 104.88647390000001)
    កាលវិភាគ៖14/4/2023
      ចន្លោះពេល៖ "ប្រចាំសប្តាហ៍"
      <!-- Google tag (gtag.js) -->

<script async src="https://www.googletagmanager.com/gtag/js?id=GT-WFMRKFW"></script>

<script>

  window.dataLayer = window.dataLayer || [];

  function gtag(){dataLayer.push(arguments);}

  gtag('js', new Date());

  gtag('config', 'GT-WFMRKFW');

</script>
id:google-site-verification: googlee9c9e70123469956.html
   \"versionId\": \"1\"\n      },\n      \"param\": [\n        {\n          \"key\": \"environments\",\n          \"value\": {\n            \"type\": 1,\n            \"string\": \"debug\"\n          }\n        }\n      ]\n    },\n    \"clientAnnotations\": {\n      \"isEditedByUser\": true\n    },\n    \"isRequired\": true\n  }\n]\n\n\n___TESTS___\n\nscenarios: []\n\n\n___NOTES___\n\n\n\n\n"

            },

            {

                "accountId": "6083911161",

                "containerId": "108470643",

                "templateId": "11",

                "name": "GT-WFMRKFW",

                "fingerprint": "1681376775414",

                "templateData": "___INFO___\n\n{\n  \"type\": \"TAG\",\n  \"id\": \"cvt_temp_public_id\",\n  \"version\": 1,\n  \"securityGroups\": [],\n  \"displayName\": \"GT-WFMRKFW\",\n  \"brand\": {\n    \"id\": \"brand_dummy\",\n    \"displayName\": \"\"\n  },\n  \"description\": \"\",\n  \"containerContexts\": [\n    \"WEB\"\n  ]\n}\n\n\n___TEMPLATE_PARAMETERS___\n\n[\n  {\n    \"type\": \"LABEL\",\n    \"name\": \"label1\",\n    \"displayName\": \"\"\n  }\n]\n\n\n___SANDBOXED_JS_FOR_WEB_TEMPLATE___\n\n// Enter your template code here.\nconst log = require('logToConsole');\nlog('data =', data);\n\n// Call data.gtmOnSuccess when the tag is finished.\ndata.gtmOnSuccess();\n//<!-- Google tag (gtag.js) -->\n//<script async src=\"https://www.googletagmanager.com/gtag/js?id=GT-WFMRKFW\"></script>\n//<script>\n  //window.dataLayer = window.dataLayer || [];\n  //function gtag(){dataLayer.push(arguments);}\n  //gtag('js', new Date());\n\n  //gtag('config', 'GT-WFMRKFW');\n//</script>\n\n\n___WEB_PERMISSIONS___\n\n[\n  {\n    \"instance\": {\n      \"key\": {\n        \"publicId\": \"logging\",\n        \"versionId\": \"1\"\n      },\n      \"param\": [\n        {\n          \"key\": \"environments\",\n          \"value\": {\n            \"type\": 1,\n            \"string\": \"debug\"\n          }\n        }\n      ]\n    },\n    \"isRequired\": true\n  }\n]\n\n\n___TESTS___\n\nscenarios: []\n\n\n___NOTES___\n\n\n\n\n"

            }

        ]

    }

}
{

  "project_info": {

    "project_number": "244145628679",

    "project_id": "httpsrathanaphonwebsitcoin",

    "storage_bucket": "httpsrathanaphonwebsitcoin.appspot.com"

  },

  "client": [

    {

      "client_info": {

        "mobilesdk_app_id": "1:244145628679:android:a7f10297db1a854b396ca2",

        "android_client_info": {

          "package_name": "httpsrathanaphon.website.co"

        }

      },

      "oauth_client": [

        {

          "client_id": "244145628679-5lpa61gqs6naujcec6om73v6hbhrlpq7.apps.googleusercontent.com",

          "client_type": 3

        }

      ],

      "api_key": [

        {

          "current_key": "AIzaSyAZwzbBslhqIFIc2c2-wJRru9PRcwpeu7I"

        }

      ],

      "services": {

        "appinvite_service": {

          "other_platform_oauth_client": [

            {

              "client_id": "244145628679-5lpa61gqs6naujcec6om73v6hbhrlpq7.apps.googleusercontent.com",

              "client_type": 3

            }

          ]

        }

      }

    }

  ],

  "configuration_version": "4"

}

  
